version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    networks: 
      - server

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge

volumes: # 몽고 DB 데이터
  data:
    driver: local  