version: "3"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./.env:/usr/.env # env 파일 복사
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks: 
      - server

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    networks: 
      - server

  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    networks: 
      - server

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge