version: "3"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    networks: 
      - server

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge